### ISSUE TITLE
Saknar fil vid Clone från github

### ISSUE THREAD

**Issue by Reminent** [Reminent/gitarr_html#8]
när man gör en clone från github så saknas filen:
Could not find file C:\Users\johanwallin\Downloads\mysql-connector-java-5.1.38\mysql-connector-java-5.1.38-bin.jar to copy.
Wallin ska ta en titt på det och uppdatera när det är fixat så det bara går att clona och köra.

**Comment by Spenatmannen** [comment]
Fixar den ja.

**Comment by Spenatmannen** [comment]
Done. Ska fungera nu, annars prata med mig så gör jag om allt.
